### ISSUE TITLE
Database plugin not working

### ISSUE THREAD

**Issue by GeoffMurray** [archi-contribs/database-plugin#28] opened 2018-01-28 23:02 UTC
Archi V 4.1.1
Windows 10

I have some strange symptoms. I'm not sure what to look for next.

I upgraded to Archi V4.1.1 recently, and moved to a Windows 10 laptop. Unfortunately, did not keep a prior Archi version around, so I'm not sure where the problem is.

I downloaded and installed Archi. 

I downloaded and installed the sqljdbc_auth.dll file and placed it into C:\Program Files\Archi4\jre\bin.

I downloaded and installed the org.archicontribs.database_v2.0.7b.jar file into C:\Program Files\Archi4\plugins.

When I try to start up Archi as a standard user, and go to add a database entry, I get this message: 

"Unable to create the selected preference page."
"An error occurred while automatically activating bundle org.archicontribs.database (45)."

If I exit Archi, and try to run as Administrator after that, I get the same message.

If I then use Archi --> Help --> Reset to Defaults, immediately exit the restarted Archi, and then Run Archi as Administrator, I can get at the database preferences page. I create an entry like I would have for prior versions, and I try to test the link. I get a message saying that if I'm using Windows Authentication mode, I need to install that file in that directory (which I had already done). Even if I enter a legitimate username/password, it still never connects to the database. When I set logging on, the only message I see is this:

- 2018-01-28 14:37:32 ERROR  822:DBDatabaseEntryTableEditor     - Failed to check the database.
- java.sql.SQLException: Please verify the database configuration in the preferences. (with a long java traceback and no variable data in it). 

I am not able to export the archi model to the database. It simply takes no action. 

If I then exit, and re-enter Archi no matter which method (ie, Run as Administrator, or run as normal user), I get this error dialogue:

"Could Not Accept Changes"
"The currently displayed page contains invalid values".

And cannot get models from the database, or save models to it.

What else can I provide that would be helpful in diagnosing the problem? 

Thanks.

**Comment by herve91** [comment] 2018-01-29 08:21
Hi,

Per my experience, the "cannot activate bundle" is often raised when the plugin JAR file is corrupted.

At the moment, you can only check the plugin JAR file size, but I will add a md5sum that will help you to check your file integrity. 

Alternatively, you may run "archi.exe -consolelog" to open up a text console with error messages that may provide some clues about this error.

Best regards
Hervé

**Comment by GeoffMurray** [comment] 2018-01-29 15:48
Sorry - did not mean to close. Finger trouble.

**Comment by GeoffMurray** [comment] 2018-01-29 15:51
Ok - that helped. I downloaded a new copy of the database plugin. When I started Archi, and tried to create a database entry in the plugin preferences, I can create one. When I execute the "Check" function, I get this:

Jan 29, 2018 7:49:59 AM com.microsoft.sqlserver.jdbc.AuthenticationJNI <clinit>
WARNING: Failed to load the sqljdbc_auth.dll cause : C:\Program Files\Archi4\jre\bin\sqljdbc_auth.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform

I'm guessing I need a different version of that DLL?

**Comment by GeoffMurray** [comment] 2018-01-29 15:58
Ok - here's something weird. I shut down Archi, and restarted it, and also got this error. This triggered the 

"Could Not Accept Changes"
"The currently displayed page contains invalid values".

When I tried to go back into the preferences.

========
Exception in thread "checkForUpdate" java.lang.ExceptionInInitializerError
        at org.archicontribs.database.DBPlugin$1.run(DBPlugin.java:483)
Caused by: java.lang.NullPointerException
        at org.archicontribs.database.GUI.DBGui.<clinit>(DBGui.java:128)
        ... 1 more
!SESSION 2018-01-29 07:56:25.638 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_144
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -clean -consolelog

!ENTRY org.eclipse.jface 4 2 2018-01-29 07:56:54.363
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
java.lang.NoClassDefFoundError: Could not initialize class org.archicontribs.database.GUI.DBGui
        at org.archicontribs.database.preferences.DBPreferencePage.createFieldEditors(DBPreferencePage.java:94)
        at org.eclipse.jface.preference.FieldEditorPreferencePage.createContents(FieldEditorPreferencePage.java:225)
        at org.eclipse.jface.preference.PreferencePage.createControl(PreferencePage.java:241)
        at org.eclipse.jface.preference.PreferenceDialog.createPageControl(PreferenceDialog.java:1426)
        at org.eclipse.jface.preference.PreferenceDialog$8.run(PreferenceDialog.java:1193)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
        at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
        at org.eclipse.jface.preference.PreferenceDialog.showPage(PreferenceDialog.java:1185)
        at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.showPage(FilteredPreferenceDialog.java:591)
        at org.eclipse.jface.preference.PreferenceDialog$5.lambda$0(PreferenceDialog.java:657)
        at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
        at org.eclipse.jface.preference.PreferenceDialog$5.selectionChanged(PreferenceDialog.java:654)
        at org.eclipse.jface.viewers.StructuredViewer$3.run(StructuredViewer.java:872)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
        at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
        at org.eclipse.jface.viewers.StructuredViewer.firePostSelectionChanged(StructuredViewer.java:869)
        at org.eclipse.jface.viewers.StructuredViewer.handlePostSelect(StructuredViewer.java:1238)
        at org.eclipse.jface.viewers.StructuredViewer.lambda$0(StructuredViewer.java:1261)
        at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:81)
        at org.eclipse.jface.util.OpenStrategy.firePostSelectionEvent(OpenStrategy.java:261)
        at org.eclipse.jface.util.OpenStrategy.access$5(OpenStrategy.java:256)
        at org.eclipse.jface.util.OpenStrategy$1.lambda$1(OpenStrategy.java:426)
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4213)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3820)
        at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
        at org.eclipse.jface.window.Window.open(Window.java:794)
        at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.open(WorkbenchPreferenceDialog.java:211)
        at org.eclipse.ui.internal.OpenPreferencesAction.run(OpenPreferencesAction.java:63)
        at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
        at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
        at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
        at com.archimatetool.editor.Application.start(Application.java:81)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1499)

!ENTRY org.eclipse.jface 4 0 2018-01-29 07:56:57.632
!MESSAGE java.lang.NullPointerException
!STACK 0
java.lang.NullPointerException
        at org.archicontribs.database.preferences.DBPreferencePage.performOk(DBPreferencePage.java:411)
        at org.eclipse.jface.preference.PreferenceDialog$7.run(PreferenceDialog.java:902)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
        at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
        at org.eclipse.jface.preference.PreferenceDialog.okPressed(PreferenceDialog.java:886)
        at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.okPressed(FilteredPreferenceDialog.java:400)
        at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.okPressed(WorkbenchPreferenceDialog.java:168)
        at org.eclipse.jface.preference.PreferenceDialog.buttonPressed(PreferenceDialog.java:230)
        at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
        at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:81)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
        at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
        at org.eclipse.jface.window.Window.open(Window.java:794)
        at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.open(WorkbenchPreferenceDialog.java:211)
        at org.eclipse.ui.internal.OpenPreferencesAction.run(OpenPreferencesAction.java:63)
        at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
        at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
        at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
        at com.archimatetool.editor.Application.start(Application.java:81)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1499)

**Comment by GeoffMurray** [comment] 2018-01-29 16:02
If I don't check the box that requests the database plugin automatically check for updates, the corruption doesn't seem to happen. I am able to repeatedly go back into the preferences.

**Comment by herve91** [comment] 2018-01-29 16:07
Regarding the DLL, you're right. There is a 32bit and a 64 bit version. I updated both. Alternatively, you may download them directly from Microsoft [https://www.microsoft.com/fr-fr/download/details.aspx?id=11774](url)

**Comment by GeoffMurray** [comment] 2018-01-29 16:07
Ok - thanks - I did download it from the link you shared. I was able to do a db check! 

I'll try a model save to the DB now.

**Comment by herve91** [comment] 2018-01-29 16:09
The error messages you sent state a nullPointerException.

Generally, the issue is between the chair and the screen (I mean the developper ... I mean me) ...

I've got he method name and line number where the exception occurred and I will manage that this issue does not arrises in the next version. Meanwhile, you have no choice but deactivate the automatic update I'm afraid.

**Comment by GeoffMurray** [comment] 2018-01-29 16:10
Beauty! Was able to upload a model. Thanks, again, for your rapid response. 

No problem on the automatic update. I can work around for sure.

**Comment by herve91** [comment] 2018-01-29 16:13
Great :) 

So I close this issue.

Please do not hesitate to provide me with feedback (bugs, feature requests, etc ...) that I can improve my plugin.

**Closed by herve91** 2018-01-29 16:13 UTC
