### ISSUE TITLE
Database initiation

### ISSUE THREAD

**Issue by aroshdy** [archi-contribs/database-plugin#102] opened 2020-07-22 15:16 UTC
Hi,
whenever i add the connection string and press check, i got this error, and it creates 2 or 3 tables only, on debugging, found that the problem in the folders sql statement
![Capture](https://user-images.githubusercontent.com/13233605/88194193-d0b84f80-cc3e-11ea-96ae-f14201593676.PNG)

In addition the jar file of 2.2.8 is not available

**Comment by aroshdy** [comment] 2020-07-22 15:21
[DatabasePlugin.log](https://github.com/archi-contribs/database-plugin/files/4960805/DatabasePlugin.log)

**Comment by herve91** [comment] 2020-07-25 21:31
Hi,
Could you please check version 2.2.9 of the plugin. The error should be fixed.

Please note that the JAR file is not provided anymore, as Archi provides a cleaner way to install / update a plugin. Please see the readme.md file.

Best regards
Hervé

**Comment by grv87** [comment] 2020-07-27 12:54
Maybe connected problem, with Oracle: `ORA-00907: missing right parenthesis`.
I've checked both v2.2.8 and v2.2.9, the same result.

**Comment by herve91** [comment] 2020-07-27 13:28
Which version of oracle are you using ?

**Comment by grv87** [comment] 2020-07-27 13:57
@herve91, Oracle 12.2.0.1.

I'm investigating now.
Looks like the problem is here:
```
CREATE TABLE database_version (id VARCHAR(50) NOT NULL, archi_plugin VARCHAR(50) NOT NULL, version INTEGER(10) NOT NULL)
```
There is no `INTEGER(10)` in Oracle.
And my error is not connected to this issue, I should file another one.

**Comment by herve91** [comment] 2020-07-27 14:04
I did my tests on 11g and it works. I'll install a 12.2 and send you a fix asap.

**Comment by grv87** [comment] 2020-07-27 14:27
@herve91, thanks!

Here is the log:
[DatabasePlugin.log](https://github.com/archi-contribs/database-plugin/files/4982535/DatabasePlugin.log)

Should I file another issue, or you are going to continue to work in this one?

**Comment by herve91** [comment] 2020-07-27 14:30
I'm not procedural :) I do not need another issue...

**Comment by paulo59** [comment] 2020-07-31 06:59
Hello,
I got the same error with mysql 8.0.21 
![image](https://user-images.githubusercontent.com/22616492/89009031-0ed30480-d30c-11ea-8c41-b22b66f88c3d.png)

**Comment by herve91** [comment] 2020-07-31 09:08
Hi, Thanks for the information. I'll double check with MySQL version 8.0.21.

Best regards
Hervé

**Comment by grv87** [comment] 2020-07-31 12:38
@herve91, for Oracle looks like this line:
https://github.com/archi-contribs/database-plugin/blob/04725c8d5faa1e5dc324d0f438fce3ea936d4e30/v2/sources/src/org/archicontribs/database/DBColumn.java#L109
should be changed.

Unfortunately I can't build the project and test this change by myself.

But I don't see how current version could work in Oracle 11 either.

**Comment by herve91** [comment] 2020-08-05 19:04
So a lot of issues in this thread, but all related to the same bug(s) I think.

version 2.2.10 should fix all of them.

I checked with MariaDB latest version, MS SQL 2019, Oracle 11gR2.

Please tell me if you still encounter issues.

Best regards
Hervé

**Comment by grv87** [comment] 2020-08-09 12:10
@herve91, Oracle is fixed. Thanks!

BTW, I have to note two things:

1. It doesn't work for me from the box. Requires `orai18n.jar`. I had to patch `org.archicontribs.database_2.2.10.jar` manually. Maybe there is a better way to provide/replace JDBC drivers, but I couldn't find any.

2. If `Schema` is set empty then tables are created, but the following check fails saying columns are missing. Not a big problem to set `Schema`, just unexpected and not so convenient.

**Comment by herve91** [comment] 2020-08-10 07:38
@Hi Basil,

I do not understand why you need to patch the JAR file. The JDBC driver is included inside (ojdbc10.jar) and it works out of the box for me. Which version of Oracle are you using ? could you please provide me the exception raised in the log file ?

Regarding the schema, I'll double check and come back to you asap.

Best regards
Hervé

**Comment by herve91** [comment] 2020-08-10 21:30
Hi Basil,

I did some more tests and the database structure check fails on Oracle database when the schema is left empty. Nevertheless, the import and export functions work well with an empty schema.

Do you have a log file with an error message or an exception that I can investigate further ?

Best regards
Hervé

**Comment by jdsbjss** [comment] 2020-08-12 14:08
Hi, I have been trying to get this working with MariaDB and it now looks like there is syntax error with the AUTO INCREMENT statement 

![image](https://user-images.githubusercontent.com/59616914/90025117-96762700-dcad-11ea-9cd6-55fa383c402a.png)

Is there a manual work around to keep going building the schema please

**Comment by herve91** [comment] 2020-08-13 12:35
I succeeded to reproduce the issue and found the cause. I'll send a fix by the end of the week.

Best regards
Hervé

**Comment by jdsbjss** [comment] 2020-08-13 12:36
Awesome that is super kind.. If I had any java dev skills I would have debugged further sorry.


Thanks

James

**Comment by herve91** [comment] 2020-08-13 12:39
no prob :-)

I'm currently learning how to automate my test case and reduce the cases where an action on a database brand has a negative impact on another database brand.

I hope I'll be able to implement them quickly.

**Comment by herve91** [comment] 2020-08-13 22:22
tables creation fixed in version 2.2.11

I close this thread, please open a new one in case of another issue.

**Closed by herve91** 2020-08-13 22:22 UTC
Labels: bug

**Comment by grv87** [comment] 2020-08-14 03:30
@herve91, my database has NLS setting `CL8WIN1251` or something like that. In such cases `ojdbc*.jar` is not enough, `orai18n.jar` is required too.

See [here](https://docs.oracle.com/cd/B12037_01/java.101/b10979/global.htm):

>To use any other character sets in CHAR or VARCHAR data members of Objects or Collections, you must include orai18n.jar in your application's CLASSPATH.

Probably could be solved using `NVARCHAR`.

**Comment by herve91** [comment] 2020-08-14 20:03
oh, I see ...

I'll add it that it will be natively available for you in next release. you should have asked before
