### ISSUE TITLE
Tag elements or folders in order to not be exported

### ISSUE THREAD

**Issue by vbo75** [archi-contribs/database-plugin#136] opened 2021-12-07 20:20 UTC
Hi,

I am very interesting to use this plug-in in a corporate environment. I'm running tests with other colleagues to stress this collaborative ability.
Is it possible to tag some items or folders on the local model so as not to be exported to the database ?
It would be useful to keep some elements in draft state in the local model.

An another question, documentation seems to be in an old version.

Nevertheless, thank you very much for this plug-in !

**Comment by herve91** [comment] 2021-12-08 11:32
Hi Vincent,

Thank you for your interest in my plugin. You are right, I did not spent enough effort on the documentation. I promise I will increase my documentation quality in the coming weeks :)

Regarding your request, blocking the export of components would be quite very complex as a distinction will have to be made between newly created draft components (that should not be created in the database, and therefore won't be imported during next database import) and existing components with draft updates (that should not be updated in the database, but previous non draft version should be imported during next database import). This would have a ve

To be honest, it may be easier for me to add branches functionality rather than implementing your request. Would it be of some interest for you ?

**Comment by herve91** [comment] 2021-12-08 16:00
Regarding your workflow, may be you can provide a more detailed algorithm ? It's not because I do not foresee how I can do it that it necessary means that it is not feasible :) In which country are you ? Are you a French speaker ? May be we could talk about it ?

Regarding the embedded help documentation, I used to code the HTML manually which is VERY time consuming but I've found a post that explains how to install a GUI in Eclipse to edit the pages much quicker. It will help me a lot. As for the wiki, I'm searching a way to extract the plugin help pages in order to avoid doing the same pages twice.

Regarding bugs, yes please do, and do not forget to include the procedure to reproduce them and the log file in trace mode if possible (it will help me understand where the bug happens in my code). Then, I'll be happy to fix them.

**Comment by herve91** [comment] 2022-01-07 10:30
Hi Vincent,

As you may notice, I began to update the inline documentation (and will copy it to the wiki). I did not finish as it is time consuming and I preferred to release a new version today in order to provide the included fixes.

I close this case, nevertheless, I will continue to update the documentation as you requested :)

**Closed by herve91** 2022-01-07 10:30 UTC
Labels: enhancement
